FROM keiichihikita/terraform-ecl:latest

LABEL "com.github.actions.name"="terraform apply"
LABEL "com.github.actions.description"="Run Terraform Apply"
LABEL "com.github.actions.icon"="play-circle"
LABEL "com.github.actions.color"="blue"

LABEL "repository"="https://github.com/keiichi-hikita/terraform-ecl-github-actions"
LABEL "maintainer"="Keiichi Hikita <keiichi.hikita@gmail.com>"

ENTRYPOINT ["/entrypoint.sh"]
